import rc from 'rc';

export default rc('license-downloader', {

  /*
		full path to json file generated by 'license-report'
    describing all packages to handle
	*/
  source: '',

  /*
    Download license files if true,
    if false, only the paths of the license files are added to a copy
    of the source file
  */
  download: false,

  /*
		target directory for downloaded license files;
    on null or undefined a directory named 'licenses' in the directory of the
    source is used
	*/
  licDir: null,

  /*
		Name of the environment variable holding the access token ('tokenEnvVar')
    or the name of the file containing the token ('tokenFileEnvVar') for
    accessing the github api for downloading the license files;
    tokenFileEnvVar has precedence over tokenEnvVar
    Example 1: export GITHUB_TOKEN=abcdefghi
    and then: tokenEnvVar: 'GITHUB_TOKEN'
    Example 2: export GITHUB_TOKEN=/run/secrets/github_pat.txt
    content of file /run/secrets/github_pat.txt: abcdefghi
    and then: tokenFileEnvVar: 'GITHUB_TOKEN_FILE'
	*/
  githubToken: {
    tokenEnvVar: '',
    tokenFileEnvVar: ''
  },

  /*
		retry options for 'got'
	*/
  httpRetryOptions: {
    maxAttempts: 3
  }
});
