import rc from 'rc';

export default rc('license-downloader', {

  /*
		json file generated by 'license-report' describing all packages to handle
	*/
  source: '',

  /*
    Download license files
  */
  download: false,

  /*
		target directory for downloaded license files;
    on null or undefined a directory named 'licenses' in the directory of the
    source is used
	*/
  licDir: null,

  /*
		retry options for 'got'
	*/
  httpRetryOptions: {
    maxAttempts: 3
  }
});
