import rc from 'rc';

export default rc('license-downloader', {

  /*
		full path to json file generated by 'license-report'
    describing all packages to handle
	*/
  source: '',

  /*
    Download license files if true,
    if false, only the paths of the license files are added to a copy
    of the source file
  */
  download: false,

  /*
		target directory for downloaded license files;
    on null or undefined a directory named 'licenses' in the directory of the
    source is used
	*/
  licDir: null,

  /*
		retry options for 'got'
	*/
  httpRetryOptions: {
    maxAttempts: 3
  }
});
